groups:
  - name: pod_metrics
    interval: 30s  # How often to evaluate the rule
    rules:
      - record: kube_pod_info_with_name
        expr: |
          label_replace(
            kube_pod_info,
            "pod_name",
            "$1",
            "pod",
            "^([^-]+-[^-]+)-[^-]+-[^-]+$"
          )