apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: grpc
      port: 14250
      targetPort: 14250
    - name: collector
      port: 14268
      targetPort: 14268
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.8.0
          ports:
            - containerPort: 16686 # UI
            - containerPort: 14250 # gRPC
            - containerPort: 14268 # Collector HTTP
          volumeMounts:
            - name: jaeger-config
              mountPath: /etc/jaeger
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: jaeger-config
          configMap:
            name: jaeger-config 