apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger
  namespace: observability
spec:
  ports:
  - name: http-query
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: collector
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: jaeger
  type: ClusterIP
