apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jaeger"},"name":"jaeger","namespace":"observability"},"spec":{"ports":[{"name":"http-query","port":16686,"targetPort":16686},{"name":"grpc","port":14250,"targetPort":14250},{"name":"collector","port":14268,"targetPort":14268}],"selector":{"app":"jaeger"}}}
    creationTimestamp: "2025-07-09T14:53:52Z"
    labels:
      app: jaeger
    name: jaeger
    namespace: observability
    resourceVersion: "676599"
    uid: a2eb66f8-1f65-45c4-93cc-b748cf0fd08e
  spec:
    clusterIP: 10.108.46.154
    clusterIPs:
    - 10.108.46.154
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: collector
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    selector:
      app: jaeger
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
