apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitor
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging: {}

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          exporters: [logging]
